### Truncate Tables
POST http://localhost:8000/truncate-tables/
Content-Type: application/json


### Show applications
GET http://localhost:8000/api/job_posts/4/applicants/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NzcxMDc2LCJpYXQiOjE3MzU3NjcwMjAsImp0aSI6Ijk3YjkyMGZlNmYzNDQxMzY4YmM4NjJlNWRjNjNhYWE2IiwidXNlcl9pZCI6Mn0.1ZHShuN8BpaAjc019mzO1MIewXEE3bA83Mq62IQMVk0
