### Truncate Tables
POST http://localhost:8000/truncate-tables/
Content-Type: application/json


### Signup a new student
POST http://localhost:8000/auth/student/signup/
Content-Type: application/json

{
    "first_name": "Nooraldeen",
    "last_name": "Aloudat",
    "email": "nooraldeen.aloudat@gmail.com",
    "password": "123456789Nn@"
}

### Verify OTP for Student
POST http://localhost:8000/auth/student/verify_otp/
Content-Type: application/json

{
    "email": "nooraldeen.aloudat@gmail.com",
    "otp": "952170"
}

### Request a new student OTP
POST http://localhost:8000/auth/student/request_new_otp/
Content-Type: application/json

{
    "email": "nooraldeen.aloudat@gmail.com"
}


### Signup a new company
POST http://localhost:8000/auth/company/signup/
Content-Type: application/json

{
    "name": "testcompany",
    "password": "testpassword",
    "email": "noor.feraas@gmail.com"
}

### Test Verify OTP for Company
POST http://localhost:8000/auth/company/verify_otp/
Content-Type: application/json

{
    "email": "noor.feraas@gmail.com",
    "otp": "421101"
}

### Request a new company OTP
POST http://localhost:8000/auth/company/request_new_otp/
Content-Type: application/json

{
    "email": "noor.feraas@gmail.com"
}


### Test Login for Student
POST http://localhost:8000/auth/login/
Content-Type: application/json

{
    "email": "nooraldeen.aloudat@gmail.com",
    "password": "123456789Nn@"
}

### Test Login for Company
POST http://localhost:8000/auth/login/
Content-Type: application/json

{
    "email": "noor.feraas@gmail.com",
    "password": "testpassword"
}

### Is the user verified?
GET http://localhost:8000/auth/check_verification/
Authorization: Bearer 1fa4024d187fe365dae033d8c87d327001a75460

### Refresh Access Token
POST http://localhost:8000/auth/refresh_token/
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMzAzNDEzNSwiaWF0IjoxNzMyOTQ3NzM1LCJqdGkiOiJmMmU4MmQyNjdhY2Q0ODNhODAxOGM2ODgzODIzMWY1YiIsInVzZXJfaWQiOjF9.DQQ0A6ZNHIirzvlQOf7dogRt9LCgH7za32fOCyGnT3w"
}

### Test auth api call
GET http://localhost:8000/auth/api_call_success/
Authorization: Bearer 503b542bfd5d7550d8601e01eb1c4a17ed0bf6d3

### Get user data
GET http://localhost:8000/auth/user_data/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyOTQ0ODE4LCJpYXQiOjE3MzI5NDQ1MTgsImp0aSI6IjFlYzFhZjFiMTRmNjQwMGM5ZTIwYzNlZTM3ZjRlYWFkIiwidXNlcl9pZCI6MX0.QR2x1tE64X3bC2jdVegcf3Zgk36b5_L49k0JnBvsQPs

### Check the user's token
GET http://localhost:8000/auth/check_token/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyOTQ1OTY1LCJpYXQiOjE3MzI5NDU2NjUsImp0aSI6IjA5NWYwOWJjZmJmNzRhN2VhMjlhMjljY2RlYjcxYzU0IiwidXNlcl9pZCI6MX0.JW4F0n5QuMaSOm9LV9liZ6Nj73fJpLsb-b3HYS87BR0
Content-Type: application/json

### logout
POST http://localhost:8000/auth/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyOTUxODU3LCJpYXQiOjE3MzI5NTE1NTcsImp0aSI6IjZkYzQ1MDhiNmQ0ZTQ0MWZiYThlY2VlMDlhYmYwMGZmIiwidXNlcl9pZCI6MX0.OYvSme6jPcEFMTCq_9gBPOgWkY9luLGMfepAgRm0ZAU

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMzAzNzk1NywiaWF0IjoxNzMyOTUxNTU3LCJqdGkiOiIwOGRiOGQ1NWMzMjg0ZmQ2YjY2MmUzN2Y1MmIzMzY0NiIsInVzZXJfaWQiOjF9.rjFp2vqGqZo3f6ZR_1BFJM-nN3fFBEUoUiFOwkEPuKk"
}