# Generated by Django 5.1.3 on 2024-11-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
