# Generated by Django 5.1.3 on 2025-01-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='proof_document',
            field=models.URLField(blank=True, null=True),
        ),
    ]
