# Generated by Django 5.1.3 on 2024-12-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_website_url_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
