# Generated by Django 5.1.3 on 2024-12-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_company_city_remove_company_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='website_url',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
