# Generated by Django 5.1.3 on 2024-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_website_url_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
