# Generated by Django 5.1.3 on 2024-12-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0002_remove_education_students_education_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
