# Generated by Django 5.1.3 on 2024-12-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_major_student_department'),
        ('universities', '0003_remove_department_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
