# Generated by Django 5.1.3 on 2025-01-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
