# Generated by Django 5.1.3 on 2024-12-27 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('jobs', '0002_remove_application_resume_id_application_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='location',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='departments.department'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
