# Generated by Django 5.1.3 on 2025-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='is_active',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='_is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
