# Generated by Django 5.1.3 on 2024-12-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobpost_location_jobpost_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
