# Generated by Django 5.1.3 on 2024-12-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_created_at_application_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
