# Generated by Django 5.1.3 on 2024-12-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='requirements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
