### List Resumes
GET http://localhost:8000/api/resumes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MTM4ODAzLCJpYXQiOjE3MzUxMzcwMDMsImp0aSI6IjUyMGUwYzU1ODg5NDRiMWNhODc1MTFiYjVhNzI0ODRjIiwidXNlcl9pZCI6MX0.hoP-0WHrHUKU56lVWrbbKQ6udsGyvc42bqS-Y5xdEi0

### Create multiple Resumes
POST http://localhost:8000/api/resumes/
Authorization: Bearer YOUR_ACCESS_TOKEN
Content-Type: multipart/form-data

{
    "file_name": [
        "@My_CV2.pdf",
        "@English for career development.pdf"
    ],
    "student": 1
}

### Retrieve a Resume
GET http://localhost:8000/api/resumes/1/
Authorization: Bearer YOUR_ACCESS_TOKEN

### Update a Resume
PUT http://localhost:8000/api/resumes/1/
Authorization: Bearer YOUR_ACCESS_TOKEN
Content-Type: application/json

{
    "file_name": "updated_resume.pdf",
    "file_url": "https://res.cloudinary.com/your-cloudinary-account/image/upload/v1647242344/updated_resume.pdf"
}

### Delete a Resume
DELETE http://localhost:8000/api/resumes/1/
Authorization: Bearer YOUR_ACCESS_TOKEN