# Generated by Django 5.1.3 on 2024-12-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
