# Generated by Django 5.1.3 on 2025-01-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
