# Generated by Django 5.1.3 on 2024-11-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='otp_expiration',
        ),
    ]
