# Generated by Django 5.1.3 on 2024-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_major_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
