# Generated by Django 5.1.3 on 2024-12-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('students', '0006_alter_student_image_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='students', to='skills.skill'),
        ),
    ]
