# Generated by Django 5.1.3 on 2024-12-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('students', '0008_alter_student_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='skills.skill'),
        ),
    ]
