# Generated by Django 5.1.3 on 2024-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
