# Generated by Django 5.0.4 on 2024-11-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
