# Generated by Django 5.1.3 on 2024-12-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_award_created_at_award_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='end_date',
        ),
    ]
