# Generated by Django 5.1.3 on 2024-12-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_name',
            field=models.TextField(),
        ),
    ]
