# Generated by Django 5.1.3 on 2024-12-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
