# Generated by Django 5.1.3 on 2025-01-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$iycNE1cnJ8xs94k6Yw1sEw$NEsgxsi8SAYtp1horbX1UaQ81GxfvxQAggwbE5PJtNk=', max_length=255),
        ),
    ]
