# Generated by Django 5.1.3 on 2025-01-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_admin_user_admin_email_admin_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
