# Generated by Django 5.1.3 on 2025-01-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$OzNxT3NzOzKYfUWFjVjoer$RQNSQCv0NgKLI22JqiuLbFBLwmUOSroP7HhtHwCGVGY=', max_length=255),
        ),
    ]
