# Generated by Django 5.1.3 on 2025-01-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Vd5NXMaLyMkDCaK5FO2ibc$fQip5GLNgv5Ajmp5RXdxCK/VxIv+I6PoYcLf1shVofU=', max_length=255),
        ),
    ]
